/**
 * Word lists for slug generation. Two flat TS arrays — reviewable in PR
 * diffs, no external dep, no surprise drift between releases. See
 * `slug.ts` for the generator and the entropy calculation.
 *
 * Words are intentionally concrete, friendly, and unambiguous — the kind a
 * designer would pick. No proper nouns, no offensive terms, no homophones
 * across the two lists. All `^[a-z]+$` (no hyphens, no spaces, no caps).
 */

export const ADJECTIVES: readonly string[] = [
  'amber',  'ancient', 'autumn', 'azure',  'balmy',   'bare',   'beaming', 'bitter', 'blank',  'blue',
  'bold',   'breezy',  'bright', 'brilliant','brisk', 'bronze', 'brown',  'bubbly', 'busy',   'calm',
  'candid', 'careful', 'caring', 'cedar',  'chalky',  'chatty', 'cheery', 'chilly', 'clay',   'clean',
  'clever', 'cloudy',  'cobalt', 'cold',   'comely',  'cool',   'copper', 'coral',  'cosmic', 'cosy',
  'cotton', 'coy',     'crafty', 'creamy', 'crimson', 'crisp',  'curly',  'daring', 'dapper', 'darling',
  'dawn',   'dear',    'deep',   'deft',   'dewy',    'dim',    'dizzy',  'doughy', 'drowsy', 'dry',
  'dusky',  'dusty',   'eager',  'earnest','earthy',  'easy',   'eerie',  'elated', 'elder',  'electric',
  'elegant','emerald', 'empty',  'epic',   'even',    'fair',   'faint',  'fancy',  'fast',   'fearless',
  'feathery','feisty', 'fern',   'fierce', 'fiery',   'finch',  'firm',   'flaxen', 'fleet',  'floral',
  'fluffy', 'fluted',  'foamy',  'fond',   'forest',  'forge',  'fragrant','frank', 'free',   'fresh',
  'friendly','frigid', 'frilly', 'frisky', 'frosty',  'fuzzy',  'gallant','gauzy',  'gentle', 'giddy',
  'gilded', 'glad',    'glassy', 'glazed', 'gleaming','glossy', 'glowing','golden', 'graceful','grand',
  'granite','grassy',  'gray',   'great',  'green',   'grumpy', 'happy',  'hardy',  'harvest','hazy',
  'heady',  'hearty',  'heather','heavy',  'helpful', 'hidden', 'hollow', 'honest', 'honey',  'hopeful',
  'humble', 'icy',     'idle',   'imperial','indigo', 'inky',   'iron',   'ivory',  'jade',   'jaunty',
  'jazzy',  'jolly',   'joyful', 'jumbo',  'kind',    'lacy',   'lake',   'lanky',  'large',  'lavish',
  'lawful', 'lazy',    'lean',   'leafy',  'lemony',  'level',  'light',  'lilac',  'limber', 'crinkled',
  'lime',   'limpid',  'linen',  'lively', 'lofty',   'lone',   'long',   'lost',   'loud',   'lovely',
  'loyal',  'lucid',   'lucky',  'lush',   'maple',   'marble', 'mauve',  'meadow', 'meek',   'mellow',
  'merry',  'midnight','mighty', 'mild',   'milky',   'mindful','minty',  'misty',  'modest', 'moonlit',
  'mossy',  'mountain','muted',  'narrow', 'navy',    'neat',   'nimble', 'noble',  'northern','nutty',
  'oaken',  'ocean',   'olive',  'open',   'opal',    'orange', 'orchid', 'paisley','pale',   'palm',
  'patient','peachy',  'pearl',  'peppery','perky',   'piney',  'pithy',  'placid', 'plain',  'platinum',
  'playful','pleasant','plucky', 'plum',   'plump',   'polite', 'poppy',  'posh',   'precious','prim',
  'pristine','proud',  'prudent','puffy',  'pure',    'purple', 'quaint', 'quick',  'quiet',  'quirky',
  'radiant','rainy',   'rapid',  'rare',   'raspy',   'raw',    'ready',  'rich',   'ripe',   'rivery',
  'robust', 'rocky',   'rolling','rosy',   'royal',   'ruby',   'rugged', 'rustic', 'sable',  'safe',
  'saffron','sage',    'salty',  'sandy',  'sapphire','satin',  'savory', 'scarlet','scenic', 'seafoam',
  'serene', 'shadowy', 'shaggy', 'shallow','sharp',   'sheer',  'shifty', 'shiny',  'short',  'shrewd',
  'shy',    'silent',  'silken', 'silly',  'silver',  'simple', 'sincere','sleek',  'slender','slick',
  'slim',   'small',   'smoky',  'smooth', 'snappy',  'snowy',  'sober',  'soft',   'solar',  'solid',
  'somber', 'sound',   'sour',   'spicy',  'spirited','splendid','spring','sprite', 'spry',   'square',
  'stark',  'starry',  'steady', 'steely', 'stellar', 'sterling','stoic', 'stony',  'stormy', 'stout',
  'straight','strong', 'sturdy', 'subtle', 'sudden',  'sugary', 'sunlit', 'sunny',  'sunset', 'supple',
  'sure',   'sweet',   'swift',  'sylvan', 'tactile', 'tame',   'tangy',  'taupe',  'tawny',  'tender',
  'thirsty','thoughtful','thrifty','tidy', 'timely',  'tiny',   'toasty', 'tough',  'tranquil','trim',
  'true',   'trusty',  'tumbled','turquoise','twilight','umber','undulate','unique','upbeat','urban',
  'usual',  'valiant', 'vast',   'velvet', 'verdant', 'vibrant','vintage','violet', 'vivid',  'wakeful',
  'walnut', 'wandering','warm',  'wary',   'watery',  'wavy',   'wee',    'weighty','western','whimsical',
  'whiskered','white', 'whole',  'wild',   'willow',  'windy',  'winged', 'wintry', 'wise',   'witty',
  'wonder', 'woodsy',  'wooly',  'worldly','yellow',  'yielding','young', 'youthful','zealous','zesty',
  'zippy',  'agile',   'airy',   'amiable','aspen',   'avid',   'beachy', 'beloved','bonny',  'bookish',
  'boundless','arctic','briny',  'brushed','buoyant', 'cheerful','chestnut','civil','classic','cleansing',
  'climbing','cloudless','coastal','aromatic','content','coppery','cordial','courteous','cresting','curious',
  'dappled','daydream','decent', 'devoted','dignified','dimpled','diligent','dimming','dreamy', 'drifting',
  'eastern','effortless','enchanted','endless','expansive','fabled','famed','fanciful','balsam','feathered',
  'felted', 'fertile', 'festive','fitting','flickering','biscuit','fluttering','flowering','foggy','forested',
  'fortunate','foxy',  'frilled','blazing','frothy',  'galactic','garnet','genial', 'genteel','glimmering',
  'gleeful','glinting','gossamer','blissful','grateful','grounded','handy','bountiful','harmonic','harvested',
  'heartfelt','heroic','hillside','homespun','buttery','candied','illustrious','immense','celestial','industrious',
  'inviting','jovial', 'jubilant','kindly','knotted', 'languid','lavender','leisurely','cinnamon','liquid',
  'lithesome','little','lonesome','lovable','lulling','luminous','marbled','marshy','meadowy','meandering',
  'meditative','melodic','meticulous','clinking','minted','misted','mountainous','musical','mystic','nestled',
  'nightly','nostalgic','nourishing','novel','cloistered','ochre','oceanic','onyx','opaline','opulent',
];

export const NOUNS: readonly string[] = [
  'acorn',  'alcove',  'alder',  'amber',   'anchor',  'anvil',  'apple',   'apricot', 'arbor',   'archer',
  'arrow',  'ash',     'aspen',  'atlas',   'autumn',  'avenue', 'badge',   'banner',  'barn',    'basin',
  'basket', 'bay',     'beach',  'beacon',  'beam',    'bean',   'bear',    'beech',   'beetle',  'bell',
  'berry',  'birch',   'bison',  'blade',   'blossom', 'bluff',  'boat',    'bonfire', 'book',    'boot',
  'borough','boulder', 'bow',    'bowl',    'box',     'brace',  'bramble', 'branch',  'breeze',  'brick',
  'bridge', 'brink',   'brook',  'broom',   'brush',   'buckle', 'bud',     'buffalo', 'bunting', 'burrow',
  'bush',   'butter',  'cabin',  'cactus',  'cairn',   'cake',   'camel',   'campus',  'candle',  'canoe',
  'canyon', 'cape',    'caravan','cardinal','carrot',  'cart',   'cascade', 'cathedral','cattail','cavern',
  'cedar',  'cellar',  'cello',  'chalice', 'chalk',   'chant',  'chapel',  'chariot', 'cherry',  'chestnut',
  'chime',  'chip',    'chisel', 'cinder',  'circle',  'citadel','clearing','cliff',   'clock',   'cloth',
  'cloud',  'clover',  'clown',  'coast',   'cobble',  'cocoa',  'coin',    'comet',   'compass', 'cone',
  'coral',  'cork',    'cottage','cotton',  'court',   'cove',   'coyote',  'crab',    'craft',   'crag',
  'crane',  'crater',  'creek',  'crest',   'cricket', 'crocus', 'crown',   'crystal', 'cuckoo',  'cup',
  'curtain','cushion', 'cypress','daffodil','dagger',  'daisy',  'dawn',    'deer',    'delta',   'desk',
  'diamond','dock',    'dolphin','door',    'dove',    'dragon', 'dream',   'drift',   'drum',    'dune',
  'eagle',  'ear',     'easel',  'echo',    'eel',     'ember',  'engine',  'envoy',   'estuary', 'fable',
  'fairway','falcon',  'fan',    'farm',    'feather', 'fence',  'fern',    'ferry',   'fiddle',  'field',
  'finch',  'finger',  'fir',    'fire',    'flag',    'flame',  'flask',   'flax',    'fleet',   'fletcher',
  'flint',  'flock',   'flower', 'flute',   'fog',     'forge',  'fort',    'fountain','fox',     'frame',
  'frond',  'frost',   'galaxy', 'garden',  'gate',    'gem',    'giraffe', 'glacier', 'glade',   'glass',
  'glen',   'glove',   'gnat',   'goose',   'gourd',   'grain',  'granite', 'grape',   'grasshopper','grebe',
  'grotto', 'grove',   'gull',   'gully',   'hammer',  'hammock','hamlet',  'harbor',  'harp',    'harvest',
  'haven',  'hawk',    'haystack','hazel',  'hearth',  'hedge',  'helmet',  'heron',   'highland','hill',
  'hive',   'holly',   'hood',   'hoof',    'horn',    'horse',  'house',   'hummingbird','hut',  'ibis',
  'iceberg','idol',    'inlet',  'iris',    'island',  'ivy',    'jaguar',  'jasmine', 'jay',     'jewel',
  'journal','jug',     'juniper','kale',    'kayak',   'kestrel','kettle',  'key',     'kingfisher','kite',
  'knapsack','knight', 'knot',   'lace',    'ladder',  'lagoon', 'lake',    'lamp',    'lantern', 'larch',
  'lark',   'lattice', 'laurel', 'lavender','leaf',    'ledger', 'lemon',   'lighthouse','lilac', 'lily',
  'linden', 'linen',   'lion',   'loom',    'lotus',   'lupine', 'lyre',    'mallet',  'mandolin','mantle',
  'maple',  'marble',  'mare',   'marigold','marsh',   'mast',   'meadow',  'medal',   'melon',   'meridian',
  'midnight','mill',   'mint',   'mirror',  'mist',    'mockingbird','moon','moor',    'morning', 'moss',
  'moth',   'mountain','mouse',  'muffin',  'mulberry','muse',   'nectar',  'needle',  'nest',    'nettle',
  'night',  'nimbus',  'noodle', 'noon',    'nymph',   'oak',    'oar',     'oasis',   'ocean',   'olive',
  'onion',  'opal',    'orchard','orchid',  'origami', 'osprey', 'otter',   'owl',     'oyster',  'pagoda',
  'palace', 'palm',    'panda',  'pantry',  'paper',   'parade', 'parchment','parsley','partridge','passage',
  'patch',  'path',    'paw',    'peach',   'pearl',   'pebble', 'pelican', 'pen',     'pendant', 'penguin',
  'peony',  'pepper',  'petal',  'pewter',  'pier',    'pigeon', 'pillar',  'pine',    'pinion',  'pipe',
  'pixie',  'plain',   'planet', 'plate',   'plateau', 'plover', 'plum',    'pocket',  'pond',    'pony',
  'poplar', 'poppy',   'porch',  'portal',  'pottery', 'prairie','primrose','prism',   'puffin',  'pumpkin',
  'quail',  'quartz',  'quill',  'quilt',   'rabbit',  'raccoon','rainbow', 'rampart', 'ranch',   'raven',
  'reef',   'reel',    'reverie','ribbon',  'ridge',   'rill',   'ring',    'ripple',  'river',   'road',
  'robin',  'rocket',  'rose',   'rowan',   'rudder',  'rune',   'rye',     'saddle',  'sage',    'sail',
  'salt',   'sand',    'sapling','sash',    'satchel', 'savanna','scribe',  'scroll',  'sea',     'season',
  'sedge',  'seedling','shadow', 'shawl',   'shell',   'sheaf',  'shepherd','shield',  'ship',    'shore',
  'shrub',  'signal',  'silo',   'sketch',  'sky',     'slate',  'sleigh',  'sloop',   'snail',   'snow',
  'sorrel', 'sparrow', 'spark',  'spear',   'spice',   'spire',  'spool',   'spring',  'spruce',  'square',
  'stable', 'star',    'station','stem',    'steppe',  'stitch', 'stoat',   'stone',   'stork',   'storm',
  'stove',  'stream',  'street', 'string',  'sun',     'sunset', 'swallow', 'swamp',   'swan',    'sycamore',
  'table',  'tadpole', 'talon',  'tapestry','tarn',    'teal',   'tempest', 'thicket', 'thimble', 'thistle',
  'thorn',  'thread',  'thrush', 'tide',    'tiger',   'tile',   'timber',  'token',   'topaz',   'torch',
  'tortoise','tower',  'tractor','trail',   'tram',    'tree',   'trellis', 'trill',   'trout',   'tulip',
  'tundra', 'turret',  'turtle', 'twig',    'twilight','umbra',  'urn',     'valley',  'vane',    'vase',
  'velvet', 'vessel',  'vine',   'violet',  'voyage',  'wagon',  'walnut',  'warbler', 'waterfall','wave',
  'weaver', 'well',    'whale',  'wharf',   'wheat',   'wheel',  'whisker', 'willow',  'window',  'wing',
  'winter', 'wire',    'wisp',   'wolf',    'wood',    'wren',   'yacht',   'yarrow',  'yew',     'zenith',
];
